Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ass = NavAbilityAsyncHttpsClient()
ass.query(QueryOptions("a"))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m ass [38;5;241m=[39m [43mNavAbilityAsyncHttpsClient[49m[43m([49m[43m)[49m
[1;32m      2[0m ass[38;5;241m.[39mquery(QueryOptions([38;5;124m"[39m[38;5;124ma[39m[38;5;124m"[39m))

Input [0;32mIn [2][0m, in [0;36mNavAbilityAsyncHttpsClient.__init__[0;34m(self, url)[0m
[1;32m      2[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, url: [38;5;28mstr[39m [38;5;241m=[39m [38;5;124m"[39m[38;5;124mhttps://api.d1.navability.io[39m[38;5;124m"[39m) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[1;32m      3[0m     [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m()
[0;32m----> 4[0m     transport [38;5;241m=[39m [43mAIOHTTPTransport[49m(url[38;5;241m=[39murl)

[0;31mNameError[0m: name 'AIOHTTPTransport' is not defined
NameError: name 'AIOHTTPTransport' is not defined

